# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches:
      # main/develop/feature 브랜치에 푸시가 올라오면 actions 실행
      - main
      - develop
      - 'feature/**'
  pull_request:
    # develop 브랜치에 PR 올라오면 actions 실행
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
        env:
          DB_PORT: ${{ SHOPPING_MALL_ENV.DB_PORT }}
          DB_TYPE: ${{ SHOPPING_MALL_ENV.DB_TYPE }}
          DB_HOST: ${{ SHOPPING_MALL_ENV.DB_HOST }}
          DB_DATABASE: ${{ SHOPPING_MALL_ENV.DB_DATABASE }}
          DB_USERNAME: ${{ SHOPPING_MALL_ENV.DB_USERNAME }}
          DB_PASSWORD: ${{ SHOPPING_MALL_ENV.DB_PASSWORD }}
          SESSION_ID: ${{ SHOPPING_MALL_ENV.SESSION_ID }}
          COOKIE_SECRET: ${{ SHOPPING_MALL_ENV.COOKIE_SECRET }}
          TYPEORM_SEEDING_FACTORIES: ${{ SHOPPING_MALL_ENV.TYPEORM_SEEDING_FACTORIES }}
          TYPEORM_SEEDING_SEEDS=: ${{ SHOPPING_MALL_ENV.TYPEORM_SEEDING_SEEDS }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: npm install, and build
        run: |
          npm install
          npm run build
